language: python
os:
- linux
python:
- '3.6'
- '3.7'
- '3.8'
env:
- SPIDER=ilarticle
- SPIDER=isarticle
- SPIDER="not spider"
install:
- pip install -r requirements.txt -r requirements-dev.txt
script: pytest -m "$SPIDER"
jobs:
  include:
  - stage: deploy to releases
    before_deploy:
    - git config --local user.name "jmyrberg"
    - git config --local user.email "jesse.myrberg@gmail.com"
    - export RELEASE_VERSION=0.0.1dev5
    - git tag $RELEASE_VERSION
    deploy:
      provider: releases
      name: Version $RELEASE_VERSION
      tag_name: "$RELEASE_VERSION"
      prerelease: true
      api_key:
        secure: R0hmX8m1t+mMv/nBAlMETiKDbS2SXyKVutfm0FS5u5X41bSpNmEKSh4/CqGptRJ6G/DC1jtZUu3Q2vYu7nKyFkBphCmhQ9YNx0alz4X9u3j69Z4gPrrxlOoKi0SBUwUgYFkCsqaElaZ5WoZq+jOoYpLP9dE6bQdexxlYZP3kC2VcXcN7aUdrVt/nA0sSJ3OGz4AI7xzXu6w8zg/NP0MSABdh+5l59R6fJl4mAtdEJMOAMvJomBHxTykSFYToafX1xHEY8SGh4eR+NWVPwpiUK27yCTLGb9us7o509wIkJgDq8OJ00UtOWqa9v2lYlxKREe+DCoBL+ALG2jukOjWETaLf7GQrXiNrHSVGO4BUzENeeXzNppSkAwBQc02GT2pI7T+0QvUJ3TNmF6qzzbWGFI9o2LsS/hV4Ji86BlbeJQpmCGcBTo8LlphZFYHhYvwcmLCIk78cTlLjCRoE7F7Uar0/bdTsPp/uXtLKKLZIRXsTBw93bMHB6BgVmyYLnylRFjCqhgHZeSAm2hZ58LmW8Sy6nKbhL308yuD0RpmcPDpIEzS2CG3Myref2nT1rif+jTrVMMTFwgdqkjhpCQ4rjAmlCc3OmFRi3/56KoAKU//hyYlg3nerejvkY0RVCOHPWldWUVU0AliFc5IzGZ8qaO1k5oqBzEqLMnF/Fk8BxuU=
      file:
      - dist/*.tar.gz
      file_glob: true
      on:
        branch: master
        repo: jmyrberg/finscraper
      skip_cleanup: 'true'
  - stage: deploy to pypi
    provider: pypi
    user: jmyrberg
    password:
      secure: tVF03GyJRVBA4sePkb70Xyfkte84CFV6WY1dxlSFxbDFmQFS0lcxsbp7T58eI2obqOjP3hvSWwFYG4tFeDj8aNwwd5MZRNwFf9vfkDww7Rl/fV6FnPF0CJWX4CX4m4HjTKhLuuVCzLDTyYcXkdTZhx0Kbqk6uhHjBgZpJPLpdVU4iOdz5FsMm56ov7IJSKfgRBkhgfKoSF1/1Ob2NjkkbKJ6cXLE+fubcKKsLx+YdTKfddwFNsoz9f0dII2ZTC6QvJWQON0KalB7qIbNtSz3arYyD5EvdI3+ce+lkaWP50CBlRH7owKFLC9qxSXqEUOYniMgEfGnmkHR896UbBRxiOlut6i7MelP68bYV18D2twSJ+pvHpRYv6oQz+PkiQtYo06F4eTwacC7aEy9S4+sBTWOT6hWM7vN/xh9LeGc9+1ij2MgsDWgI8WTzz7WHYyAGCTyiB05WVeV9JYtE1ctac5Owm5c2oQhQaM6eOVVChh++2U5ue4IARa/iIUE1AUX326LROQHDFWnfakkNp3ZphT6IOGlemCKADzvptQ93eFeh2T0DGpUIl3dD8RMonKlrwVD6ZI97mCm9aFrZZUqCbaaXvVt1Xu+Nw5x/ZqL0MWLoczqIMJioFKd875gy7XjAim+G/16evwNvu1BoyFjqKFmoKLzoXHEz5An8dTZ1Go=
    on:
      branch: master
      tags: true
      distributions: sdist
      repo: jmyrberg/finscraper
    skip_cleanup: true
