name: Draft release

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_PAT }}
      - name: Build and upload distribution to Test PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build --sdist --wheel --outdir dist/ .
          twine upload -r testpypi dist/*
          