name: Draft release

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  update-release-draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_PAT }}