name: Python package

on:
  pull_request:
    branches: [ master ]

jobs:
  scope:
    name: Prepare matrix for testing
    runs-on: ubuntu-latest
    outputs:
      spiders: ${{ steps.scope.outputs.spiders }}
    steps:
    - uses: actions/checkout@v3
    - name: Find test scope
      id: scope
      run: |
        branchName=${GITHUB_REF#refs/heads/}
        spiderName=${branchName%%/*}
        allSpiders=$(cat SPIDERS | jq -R -s -c 'split("\n")')
        echo "$allSpiders"
        isSpiderBranch=$(jq --arg spiderName "$spiderName" '.index("ilarticle")' <<< "$allSpiders")
        echo "$isSpiderBranch"
        echo "::set-output name=spiders::$allSpiders"

  test:
    name: Test
    needs: [scope]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        spider: ${{ fromJson(needs.scope.outputs.spiders) }}
    env:
      SPIDER: ${{ matrix.spider }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest -v -m "$SPIDER"
