name: Upload distribution to PyPi

on:
  push:
    branches: [feature/use-versioneer]

jobs:
  test-build:
    name: Draft release and upload distribution to Test PyPi
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Build and upload distribution to Test PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build --sdist --wheel --outdir dist/ .
          twine upload -r testpypi dist/*
